apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: discovery-operator
  name: discovery-operator
  namespace: tectonic-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      k8s-app: discovery-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: discovery-operator
    spec:
      containers:
      - image: docker.io/fabianvf/discovery-operator
        imagePullPolicy: Always
        name: discovery-operator
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
